name: Feature request
description: A new capability or contract change.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user pain are we solving?
      placeholder: "Example: Need in-memory transcription for API workloads to avoid temp files."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: What do you want added/changed? Keep it concrete.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints / non-goals
      description: What must remain true? What is explicitly out of scope?
      placeholder: |
        Constraints:
        - …
        Non-goals:
        - …
    validations:
      required: false

  - type: textarea
    id: dod
    attributes:
      label: Definition of done (testable)
      description: Acceptance criteria and how we'll validate it.
      placeholder: |
        DoD:
        - …
        Local validation:
        - ./scripts/ci-local.sh fast
        - …
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature area
      description: Which area does this feature relate to?
      options:
        - Transcription (ASR)
        - Diarization (Speaker ID)
        - Audio Enrichment (Prosody/Emotion)
        - Semantic Annotation
        - Streaming
        - Post-Processing
        - CLI
        - API
        - Export/Output Formats
        - Benchmarks
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: surfaces
    attributes:
      label: Likely surfaces touched (optional)
      description: Files/modules/CLI/API surfaces you expect to change.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
