#!/usr/bin/env python3
"""Write deterministic package-local build identity from explicit inputs."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

_SOURCE_COMMIT_PATTERN = re.compile(r"^[0-9A-Fa-f]{7,64}$")
_BUILD_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "transcription" / "_build_info.py"


def normalize_source_commit(value: str | None) -> str | None:
    if value is None:
        return None
    candidate = value.strip()
    if _SOURCE_COMMIT_PATTERN.fullmatch(candidate) is None:
        raise ValueError("source commit must be a 7-64 character hexadecimal revision")
    return candidate.lower()[:12]


def normalize_build_id(value: str | None) -> str | None:
    if value is None:
        return None
    candidate = value.strip()
    if _BUILD_ID_PATTERN.fullmatch(candidate) is None:
        raise ValueError(
            "build ID must be 1-128 characters using letters, digits, '.', '_', or '-'"
        )
    return candidate


def _python_literal(value: str | None) -> str:
    if value is None:
        return "None"
    return json.dumps(value, ensure_ascii=True)


def render_build_info(
    *,
    source_commit: str | None,
    build_id: str | None,
) -> str:
    """Render byte-stable Python source for the package-local metadata module."""
    normalized_commit = normalize_source_commit(source_commit)
    normalized_build_id = normalize_build_id(build_id)
    return (
        '"""Package-local build identity.\n\n'
        "Generated by scripts/write_build_info.py from explicit build inputs.\n"
        '"""\n\n'
        "BUILD_INFO_VERSION = 1\n"
        f"SOURCE_COMMIT: str | None = {_python_literal(normalized_commit)}\n"
        f"BUILD_ID: str | None = {_python_literal(normalized_build_id)}\n"
    )


def write_build_info(
    output: Path,
    *,
    source_commit: str | None,
    build_id: str | None,
) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_build_info(
            source_commit=source_commit,
            build_id=build_id,
        ),
        encoding="utf-8",
        newline="\n",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Write deterministic build identity into the runtime package",
    )
    parser.add_argument("--source-commit")
    parser.add_argument("--build-id")
    parser.add_argument("--output", type=Path, default=_DEFAULT_OUTPUT)
    args = parser.parse_args()

    try:
        write_build_info(
            args.output,
            source_commit=args.source_commit,
            build_id=args.build_id,
        )
    except ValueError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
